name: CI

# Controls when the workflow will run
on:
  push:
    branches:
      - master
      - main
  pull_request:
      types: [opened, synchronize, edited, ready_for_review]

permissions: read-all

jobs:
  build:
    name: Build Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Node.js environment
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Unit tests
        run: npm run test:ci

      - name: Check for E2E
        id: check-for-e2e
        run: |
          if [ -d "cypress" ]
          then
            echo "has-e2e=true" >> $GITHUB_OUTPUT
          fi

      - name: Start E2E server
        if: steps.check-for-e2e.outputs.has-e2e == 'true'
        run: npm run dev &

      - name: Run E2E tests
        if: steps.check-for-e2e.outputs.has-e2e == 'true'
        run: npm run e2e

      - name: Merge coverage
        if: steps.check-for-e2e.outputs.has-e2e == 'true'
        run: npm run report:combined

      - name: upload coverage to Codecov
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4
        if: steps.check-for-e2e.outputs.has-e2e == 'true'
        with:
          fail_ci_if_error: false
          flags: "integration"
          file: coverage/clover.xml
          token: ${{ secrets.CODECOV_TOKEN }} # required
          verbose: true # optional (default = false)

      - name: Archive E2E output
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: steps.check-for-e2e.outputs.has-e2e == 'true' && steps.run-e2e-tests.outcome != 'success'
        with:
          name: cypress-videos
          path: cypress/videos
          retention-days: 5

      - name: Store the artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: js-package
          path: dist/
          retention-days: 5
